---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: node1
  labels:
    app: kubespray
    cluster: kubespray
    kubevirt.io/os: linux
spec:
  running: true
  dataVolumeTemplates:
  - metadata:
      name: node1-pvc-vdb
      annotations:
        kubevirt.io/provisionOnNode: node4
      labels:
        app: kubespray
    spec:
      source:
        blank: {}
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 64G
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64G
        storageClassName: hostpath-provisioner
      persistentVolumeReclaimPolicy: Delete
      storageClassName: hostpath-provisioner
      volumeMode: Block
  - metadata:
      name: node1-pvc-vdc
      annotations:
        kubevirt.io/provisionOnNode: node4
      labels:
        app: kubespray
    spec:
      source:
        blank: {}
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 64G
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64G
        storageClassName: hostpath-provisioner
      persistentVolumeReclaimPolicy: Delete
      storageClassName: hostpath-provisioner
      volumeMode: Block
  - metadata:
      name: node1-pvc-vda
      annotations:
        kubevirt.io/provisionOnNode: node4
      labels:
        app: kubespray
    spec:
      source:
        registry:
          url: "docker://quay.io/containercraft/fedora:34"
          imagePullPolicy: IfNotPresent
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 64G
      config:
        featureGates:
        - HonorWaitForFirstConsumer
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 64G
        storageClassName: hostpath-provisioner
      persistentVolumeReclaimPolicy: Delete
      storageClassName: hostpath-provisioner
      volumeMode: Block
  template:
    spec:
      evictionStrategy: LiveMigrate
      nodeSelector:
        kargo-zone.containercraft.io/d: ""
      domain:
        clock:
          timer: {}
          utc: {}
        cpu:
          cores: 4
          threads: 2
          sockets: 2
          model: host-passthrough
          dedicatedCpuPlacement: false
        resources:
          requests:
            memory: 16G
            devices.kubevirt.io/kvm: "1"
          limits:
            memory: 16G
        machine:
          type: pc-q35-rhel8.3.0
        devices:
          autoattachPodInterface: false
          autoattachSerialConsole: true
          autoattachGraphicsDevice: true
          networkInterfaceMultiqueue: true
          rng: {}
          disks:
            - name: node1-disk-vda
              bootOrder: 1
              disk:
                bus: virtio
            - name: node1-disk-vdb
              disk:
                bus: virtio
            - name: node1-disk-vdc
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: eth0
            model: virtio
            macAddress: 02:d1:76:00:00:20
            bridge: {}
      hostname: node1
      networks:
      - name: eth0
        multus:
          networkName: '{{ include "kubespray.fullname" . }}.brvpc{{ .Values.network.host_interface }}.{{ .Values.network.vlan_id }}'
      terminationGracePeriodSeconds: 0
      volumes:
        - name: node1-disk-vda
          dataVolume:
            name: node1-pvc-vda
        - name: node1-disk-vdb
          dataVolume:
            name: node1-pvc-vdb
        - name: node1-disk-vdc
          dataVolume:
            name: node1-pvc-vdc
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: fedora-cloudinit-userdata
            networkDataSecretRef:
              name: node1-cloudinit-networkdata
